### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/working-with-glamorous#4]
## Todo

- [ ] Make sure all `redux` code is covered.
- [ ] Make sure all _transitions_ are covered for `<SearchBar />` animation/transition effects.
- [ ] Make sure all functionality of the `<SearchBar />` is covered.
