### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/working-with-glamorous#5]
## Todo

- [ ] Internal docs
- [ ] External docs

## README

- [ ] Link code used for `<SearchBar />`.
- [ ] Credit author of original code.
- [ ] Link to `next`, `glamorous`, `glamorous-website`.
