### ISSUE TITLE
Final Stuff

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/working-with-glamorous#6]
## Todo

- [ ] Cleanup styling.
- [ ] Deploy to Zeit.
- [ ] Scale the website ???
- [ ] Fork `glamorous`, update README example section, open PR.
- [ ] Write Medium article (add to my website as well)
- [ ] Screencast ????
